---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: swagger
  name: swagger
spec:
  ports:
  - port: 5555
    protocol: TCP
    targetPort: 5555
  selector:
    app: swagger
  type: NodePort
