version: '3.9'

services:

  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    # volumes:
    #   - ./data/db:/data/db
    networks:
      - backend

  api:
    build: ./
    ports:
      - 5000:5000
    volumes:
      - ./src:/src
    depends_on:
      - "mongodb"
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
